### ISSUE TITLE
Map local data: Column not displayed in the auto map

### ISSUE THREAD

**Issue by spanta28** [MRN-Code/coinstac#1516] opened 2022-10-01 04:04 UTC
## Task Description
Covariates file has isControl,age,gender and only age,gender are displayed. isControl is not displayed. 

![Image](https://user-images.githubusercontent.com/5415931/193387381-83529eb7-cf14-4112-a8a0-861fe370e85c.png)

## Steps to Reproduce
Just use sample data and automap. This may or may not be reproducible unless a specific covariates file is used. Please check anyways. The map local data UI is very finicky.

**Comment by kalitopix** [comment] 2022-10-10 17:01
@spanta28 Please provide me the covariates file that caused this bug. Cannot reproduce

**Comment by rssk** [comment] 2022-10-21 16:25
This is likely due to an auto map that failed, fixed by another PR closing for now

**Closed as completed by rssk** 2022-10-21 16:25 UTC
Labels: ui or ux or client
